### PR TITLE
Update beam_search_step_op_kernels.h

### PR DESCRIPTION
**Pull request by zh794390558**

### CODE REVIEW

**Comment by jonathanasdf** [comment]
hyp_id should be the index of the hyp in the beam so I believe the current documentation is correct

**Comment by zh794390558** [comment]
It is confusion that the hyp_id point to this hyp or prev hyp.

**Comment by jonathanasdf** [comment]
it's a general hyp id, and can be used for representing current or previous hyp

**Comment by zh794390558** [comment]
In the beam search code, the hyp_id is only used to point the previous hyp.

**Comment by ruomingp** [comment]
Hyp can represent a previous hypothesis or a hypothesis for the current time step, depending on the context. For example, in ComputeTopKPlusM(), "hyps" represent previous hyps, while "top_k" and "extra_m" represent the hyps for the current time step.

So I don't think we need this change.

**Comment by zh794390558** [comment]
Sorry, I am not clear of this.  

https://github.com/tensorflow/lingvo/blob/master/lingvo/core/ops/beam_search_step_op_kernels.cc#L193 the hyp_id in topk is point to prev hyps.

https://github.com/tensorflow/lingvo/blob/master/lingvo/core/ops/beam_search_step_op_kernels.cc#L239 . top_k and extra_m all are coming from merged_topk_vec.

https://github.com/tensorflow/lingvo/blob/master/lingvo/core/ops/beam_search_step_op_kernels.cc#L317 . use hyp_id to backtrack the hypothesis.

So i think the Hyp.hyp_id is only point to prev  hypothesis, all for top_k and extra_m.

The hyp_id in https://github.com/tensorflow/lingvo/blob/6f25b0d4939d0a99b9c73a52fcb1e763e28cdca1/lingvo/core/ops/beam_search_step_op_kernels.cc#L147 is fixed for hyps position.

**Pull request closed without merging**
